---
- name: create Alfresco DB
  mysql_db:
    name: "{{alfresco_db_name}}"
    state: present

- name: create Alfresco user on DB
  mysql_user:
    name: "{{alfresco_db_user}}"
    password: "{{alfresco_db_pass}}"
    host: '%'
    state: present
    priv: '{{alfresco_db_name}}.*:ALL,GRANT'
...