- name: Install MySQL 5.7 repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

- name: Install MySQL 5.7
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
     - mysql-community-server
     - mysql-community-client
     - MySQL-python

- name: Change password policy (validate_password plugin)
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'plugin-load-add=validate_password.so'

- name: Change password policy (validate_password_policy LOW)
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'validate_password_policy=LOW'

- name: Increase max connections
  lineinfile:
    path: /etc/my.cnf
    state: present
    insertafter: EOF
    line: 'max_connections=300'

- name: Start the MySQL service
  service: name=mysqld state=started enabled=true
  register: mysql_start

- name: Get MySql root password from mysql.log
  shell: awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'
  register: mysql_default_password

- debug:
    var: mysql_default_password

- name: Set root password if found in mysql.log
  shell: mysql -uroot -p"{{mysql_default_password.stdout}}" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{mysql_root_password}}'; flush privileges; "
  when: mysql_default_password is defined 
  register: mysql_root_password_changed
  notify: restart mysqld

- debug:
    msg: "Root password was read from mysql.log and changed"
  when: mysql_root_password_changed is defined

- name: Create .my.cnf file
  template:
    src: "client.my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- meta: flush_handlers
