---
- name: Create {{ acs_user }} user account
  user:
    name: "{{ acs_user }}"
    shell: /bin/bash

- name: Create {{ acs_install_folder }}
  file:
    path: "{{ acs_install_folder }}"
    state: directory
    owner: "{{ acs_user }}"
    group: "{{ acs_user }}"
    mode: 0755
    recurse: yes
    
- name: Creates other Alfresco folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
  with_items:
    - "{{ acs_install_folder }}/modules/platform"
    - "{{ acs_install_folder }}/modules/share"
    - "{{ acs_install_folder }}/alf_data/contentstore"
    - "{{ acs_install_folder }}/alf_data/contentstore.deleted"
    - "{{ acs_install_folder }}/alf_data/solr6Backup/alfresco"
    - "{{ acs_install_folder }}/alf_data/solr6Backup/archive"
    - "{{ acs_install_folder }}/scripts"
    - "{{ catalina_home_folder }}"
    - "{{ catalina_home_folder }}/lib"
    - "{{ catalina_home_folder }}/webapps"    


- name: Download MySQL jdbc driver 5.1.40
  get_url:
   url: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.40/mysql-connector-java-5.1.40.jar
   dest: "{{ catalina_home_folder }}/lib/mysql-connector-java-5.1.40.jar"
   checksum: md5:ee039ffdcd65dec90eb8fd783748e016
   mode: 0444
  when: rdbms_vendor == "mysql"

- name: Download Alfresco Content Services 6.1.0 (distribution zip)
  get_url:
   url: https://artifacts.alfresco.com/nexus/content/groups/internal/org/alfresco/alfresco-content-services-distribution/6.1.0/alfresco-content-services-distribution-6.1.0.zip
   dest: "{{ acs_install_folder }}/alfresco-content-services-distribution-6.1.0.zip"
   checksum: md5:8c649afb76e9942762376b5b62a10592
   mode: 0444
   url_username: "{{ nexus_user }}"
   url_password: "{{ nexus_password }}"
  no_log: true
  when: download_from_maven == true

- name: untar instllation
  unarchive:
    src: '{{ acs_install_folder }}/alfresco-content-services-distribution-6.1.0.zip'
    dest: "{{ acs_install_folder }}"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    creates: '{{ acs_install_folder }}/web-server/webapps/alfresco.war'

- name: Clear up downloaded ACS binary
  file:
    path: "{{ acs_install_folder }}/alfresco-content-services-distribution-6.1.0.zip"
    state: absent
  when: download_from_maven == true

- name: Copy share.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/share.war"
    dest: "{{ catalina_home_folder }}/webapps/share.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

- name: Copy alfresco.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/alfresco.war"
    dest: "{{ catalina_home_folder }}/webapps/alfresco.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

- name: Copy ROOT.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/ROOT.war"
    dest: "{{ catalina_home_folder }}/webapps/ROOT.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

- name: Copy _vti_bin.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/_vti_bin.war"
    dest: "{{ catalina_home_folder }}/webapps/_vti_bin.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

