---
   
- name: Creates other Alfresco folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
  with_items:
    - "{{ acs_install_folder }}/modules/platform"
    - "{{ acs_install_folder }}/modules/share"
    - "{{ acs_install_folder }}/alf_data/contentstore"
    - "{{ acs_install_folder }}/alf_data/contentstore.deleted"
    - "{{ acs_install_folder }}/alf_data/solr6Backup/alfresco"
    - "{{ acs_install_folder }}/alf_data/solr6Backup/archive"
    - "{{ acs_install_folder }}/scripts"
    - "{{ catalina_home_folder }}"
    - "{{ catalina_home_folder }}/lib"
    - "{{ catalina_home_folder }}/webapps"    


- name: Download MySQL jdbc driver 5.1.40
  get_url:
   url: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.40/mysql-connector-java-5.1.40.jar
   dest: "{{ catalina_home_folder }}/lib/mysql-connector-java-5.1.40.jar"
   checksum: md5:ee039ffdcd65dec90eb8fd783748e016
   mode: 0444
  when: rdbms_vendor == "mysql"

- name: Copy share.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/share.war"
    dest: "{{ catalina_home_folder }}/webapps/share.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

- name: Copy alfresco.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/alfresco.war"
    dest: "{{ catalina_home_folder }}/webapps/alfresco.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

- name: Copy ROOT.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/ROOT.war"
    dest: "{{ catalina_home_folder }}/webapps/ROOT.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

- name: Copy _vti_bin.war to {{ catalina_home_folder }}/webapps
  copy:
    src: "{{ acs_install_folder }}/web-server/webapps/_vti_bin.war"
    dest: "{{ catalina_home_folder }}/webapps/_vti_bin.war"
    owner: "{{ acs_user }}"
    group: "{{ acs_group }}"
    remote_src: yes

